server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: admin
      password: $2a$12$J2hAgn1KnzCJ0xBTWftWke.dmQCHiL4HNjMgnMqXJ/hPVu33Y7MRy

app:
  security:
    jwtSecret: $2a$12$J2hAgn1KnzCJ0xBTWftWke.dmQCHiL4HNjMgnMqXJ/hPVu33Y7MRy
    jwtExpirationInMs: 604800000
