version: '3.10'
services:
  app:
    container_name: app_container
    image: openjdk:17
    ports:
      - "${APP_PORT:-9090}:8080"
    volumes:
      - ./target:/app
    command: ["java", "-jar", "/app/icsnetwork-0.0.1-SNAPSHOT.jar"]
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/health || exit 1
      interval: 5s
      retries: 25
      start_period: 5s
      timeout: 60s

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/var/www/static:ro
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy

volumes:
  postgres:
  pgadmin:
