name: CI/CD
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker images
        run: cd icsnetwork && docker compose build

      - name: Deploy locally
        run: cd icsnetwork && docker compose up -d
